---
title: "ESM 244 Assignment 1: Task 1"
author: "Meghan Fletcher"
date: "1/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(janitor)
library(here)

# For ggplot customization:
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

# To make compound figures:
library(patchwork)
```


```{r}
# Part 1: Find the total number of adult, subadult, and tadpole yellow-legged frogs observed in the entire study region by life stage and year. Do not use the lake ID or amphibian_location in your analyses as additional grouping variables.

total_frogs <- read_excel(here("data", "sierra_amphibians.xlsx")) %>% 
  select(survey_date, amphibian_species, amphibian_life_stage, amphibian_number) %>% 
  drop_na() %>% 
  filter(amphibian_species == "RAMU") %>% 
  mutate(date = ymd(survey_date)) %>% 
  mutate(record_year = year(date)) %>% 
  count(amphibian_life_stage, record_year) %>% 
  filter(amphibian_life_stage != "EggMass")
```

```{r}
# Create a graph of the total **mountain yellow-legged frog (*Rana muscosa*) count** from each year across all water bodies by life stage - excluding the 'EggMass' level.

graph_1 <- ggplot(data = total_frogs, aes(x = record_year, y = n)) +
  geom_line(aes(color = amphibian_life_stage)) +
  labs(x = "Year", y = "Number of Frogs", title = "Total Number of Mountain Yellow-Legged Frogs in the Sierra Nevadas", subtitle = "Data collected from 1995-2002", color = "Life Stage")  +
  theme_bw() +
  coord_cartesian(ylim = c(0,500), xlim = c(1995, 2002.1)) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0), breaks = c(1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002)) +
  theme(legend.background = element_rect(fill="lightblue",
                                  size=0.5, linetype="solid", 
                                  colour ="black"))
```

```{r}
# Part 2: Find the total counts (over all years of the study) of combined adult and subadult endangered mountain yellow-legged frogs (Rana muscosa) observed in the 5 lakes with the greatest total observed counts. (OK to have more if there are ties)

# wrangle the data to create appropriate data set

adult_frogs <- read_excel(here("data", "sierra_amphibians.xlsx")) %>% 
  filter(amphibian_species == "RAMU") %>% 
  filter(amphibian_life_stage == c("Adult", "SubAdult")) %>% 
  mutate(lake = case_when(TRUE~"Lake")) %>% 
  unite(col = lake_id, c(lake, lake_id), sep = " ") %>%
  group_by(lake_id) %>% 
  summarize(total_amphibians = sum(amphibian_number)) %>% 
  slice_max(total_amphibians, n = 5)
```

```{r}
# Create graph of lakes with highest combined adult and subadult mountain yellow-legged frogs

graph_2 <- ggplot(data = adult_frogs, aes(x = fct_reorder(lake_id, total_amphibians), y = total_amphibians)) +
  geom_col(fill= "paleturquoise2") +
  labs(x = "Lake ID", y = "Total Adult & Subadult Frogs", title = "Lakes Containing the Most Adult/Subadult Mountain Yellow-Legged Frogs", subtitle = "Data collected from 1995-2002") +
  theme_bw() +
  geom_text(aes(label=total_amphibians, vjust = 2)) +
  scale_y_continuous(expand = c(0,0)) +
  geom_text(aes(x=1, y=1700, label="Stretch it"), vjust=-5)
```

```{r, fig.cap="**Figure 1:** Data was collected within the southern Sierra Nevada mountains under the Sierra Lakes Inventory Porject. The top graph shows the occurence of the life stages (adult, subadult and tadpole) of mountain yellow-legged frogs recorded by Dr. Knapp and his team from 1995 to 2002. The bottom graph reveals the 5 lakes that had the largest recorded combined subadult and adult populations of mountain yellow-legged frogs from 1995 to 2002 (Data: Knapp et al.)."}

# Combine both graphs from above using the 'patchwork' function
graph_3 <- (graph_1 / graph_2) 

graph_3

```

#### **Data citation:** Knapp, R.A., C. Pavelka, E.E. Hegeman, and T.C. Smith. 2020. The Sierra Lakes Inventory Project: Non-Native fish and community composition of lakes and ponds in the Sierra Nevada, California ver 2. Environmental Data Initiative. https://doi.org/10.6073/pasta/d835832d7fd00d9e4466e44eea87fab3
















